project_id = "cfelpyucqllkshmlkwxz"

[functions.analyze-website]
verify_jwt = false

[functions.enhance-search]
verify_jwt = false

[functions.search-places]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.get-customer-email]
verify_jwt = false