project_id = "engage"

[api]
port = 54321
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://detectify.engageai.pro"
additional_redirect_urls = [
  "https://detectify.engageai.pro",
  "https://detectify.engageai.pro/**",
  "https://detectify.engageai.pro/reset-password",
  "https://detectify.engageai.pro/reset-password/**",
  "http://localhost:3000",
  "https://gptengineer.app",
  "https://lovable.dev",
  "https://detectifys.engageai.pro",
  "https://d261f35a-a484-4323-82d8-e28223e9f6af.lovableproject.com",
  "https://d261f35a-a484-4323-82d8-e28223e9f6af.lovableproject.com/**"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
[functions.analyze-website]
verify_jwt = false

[functions.search-places]
verify_jwt = false

[functions.enhance-search]
verify_jwt = false

[functions.get-secret]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.get-customer-email]
verify_jwt = false

[functions.create-guest-checkout]
verify_jwt = false