
project_id = "cfelpyucqllkshmlkwxz"

[deploy]
allow_net = ["*"]

[http_server]
port = 54321
headers = [
  "Access-Control-Allow-Origin: *",
  "Access-Control-Allow-Headers: authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods: GET, POST, OPTIONS"
]
