
project_id = "engage"

[deploy]
allow_net = [
  "maps.googleapis.com",
  "*.google.com",
  "*"
]

[http_server]
port = 54321
headers = [
  "Access-Control-Allow-Origin: *",
  "Access-Control-Allow-Headers: authorization, x-client-info, apikey, content-type, x-application-name",
  "Access-Control-Allow-Methods: GET, POST, OPTIONS",
  "Content-Type: application/json"
]
