export const basicChatPatterns = [
  /chat-widget/i,
  /chat-container/i,
  /chat-box/i,
  /chat-frame/i,
  /chat-button/i,
  /chat-messenger/i,
  /chat-popup/i,
  /chat-window/i,
  /chat-launcher/i,
  /chat-trigger/i,
  /widget\.js.*chat/i,
  /chat.*widget\.js/i,
  /chat.*messenger/i,
  /messenger.*chat/i,
];